# Generated by Django 3.1.5 on 2021-01-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memo', models.CharField(max_length=50)),
                ('not_clear', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkbook.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkbook.category')),
            ],
        ),
    ]
